name: Data Import

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run scripts
        run: |
          python ./script/data_import.py

      - name: Check file
        run: cat ./data/now.json

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update now.json
          title: Update now.json
          labels: auto_merge
          branch-suffix: 'short-commit-hash'