name: Deploy Script

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.9]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out
        uses: actions/checkout@v2

      - name: Install package
        run: |
          sudo apt update
          sudo apt install tree
          npm install -g aws-cdk
          pip install -r requirements.txt

      - name: CI and Build
        run: |
          npm ci
          npm run build --if-present
          tree

      - name: Deploy
        run: cdk deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'